---
title: "NYC Condom Distribution"
output: html_document
---

[Click for a cute surprise](images/condom_cartoon.jpeg)

## Motivation

The motivation for this project is to explore the distribution of free condoms across different areas in NYC. We want to determine areas of the city where more free condoms can be distributed, and ensure that equal amounts are being distributed for both females and males. We also would like to explore whether certain types of venues have made more of an effort to distribute free condoms than others.

## Contents of this Website

* [Interactive Map]()
* [Male and Female Condom Availability](female_male_condoms.html): Explores what venues male and female condoms can be found at
* [Venues per Borough](venues_across_boroughs.html): Explores what types of venues are located in each borough of NYC
* [Popular Venues](popular_venues.html): Explores which types of venues have the most distribution locations
* [Screencast]
* Many people do not know what female condoms are or how to use them. Check out this short, informative [video](https://youtu.be/DBZ7xeT1j6M) to learn more about them!
* For how to use male condoms, check out this short [video](https://youtu.be/1I2nyyVcicA)!