---
title: "lm"
author: "Daniela Rochez"
date: "12/9/2021"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
condom_data = 
  GET("https://data.cityofnewyork.us/resource/4kpn-sezh.csv") %>% 
  content("parsed")
cleaned_data = 
  condom_data %>% 
  select(facility_pk, facilityname, partnertype, partner_type_detailed, 
         address, borough, zipcode, latitude, longitude, phone, condoms_male,
         fc2_female_insertive_condoms, lubricant) %>% 
  rename(condoms_female = fc2_female_insertive_condoms) %>% 
  rename(partner_subtype = partner_type_detailed) %>% 
  mutate(
    condoms_male = as.factor(condoms_male), 
    condoms_male = fct_recode(condoms_male, "0" = "FALSE", "1" = "TRUE"),
    condoms_female = as.factor(condoms_female),
    condoms_female = fct_recode(condoms_female, "0" = "FALSE", "1" = "TRUE"),
    lubricant = as.factor(lubricant),
    lubricant = fct_recode(lubricant, "0" = "FALSE", "1" = "TRUE"),
    borough = as.factor(borough)
  )

cleaned_data$partnertype[cleaned_data$partnertype == "Community Based Organization/Non-Profit"] =
  "Community-Based Organization/Non-Profit"
```

```{r setup, include=FALSE}
female_condom_logistic =
  cleaned_data %>% 
  glm(condoms_female~borough+partnertype+
        partner_subtype, data = ., family = binomial())

female_condom_logistic_df =
  female_condom_logistic %>% 
  broom::tidy() %>%
  select(term, estimate,p.value) 

view(female_condom_logistic_df)
```

