---
title: "Proposal"
author: "Malvika, Amy, Dani and Saryu "
date: "11/12/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Group members
Malvika Venkataraman (msv1237)

Amy Liu (fl2569)

Dani Rochez (dr3168)

Saryu Patel (sp4029)

### Tentative project title
Availability of Free Condoms in NYC

### Motivation
The motivation for this project is to explore the distribution of free condoms across different areas in NYC. We want to determine areas of the city where more free condoms can be distributed, and ensure that equal amounts are being distributed for both females and males. We also would like to explore whether certain organizations have made more of an effort to distribute free condoms than others.

### Intended final products
A website with a report on our findings, complete with visualizations and interactive maps.

### Anticipated data source
The "NYC Condom Availability Program - HIV condom distribution locations" dataset from NYC Open Data. The dataset includes a list of over 325 venues, across the five boroughs that actively distribute free safer sex products.

### The planned analyses / visualizations / coding challenges
Our plan is to read in the data, clean it, manipulate it, create summary statistics, do exploratory data analysis, answer the main questions of our analysis, explore new questions that come up, create interactive maps, and other interactive visualizations.

Some of the example questions we want to examine are: 

* How do the number of venues vary per borough?
* How does the availability of products for females and males vary per venue?
* How does the availability of products for females and males vary per borough?
* What is the breakdown of condom distribution per organization type?
* What is the most popular venue type to distribute condoms?

A challenge we might encounter is that if want to explore questions related to the day of the week, it will be difficult because there is a lot of missing data in the variables on each day of the week. Another challenge is related to collaborative coding. We all have different coding styles and will have to communicate on our naming conventions and approach.

### Planned timeline
Our planned timeline is as follows:

* By November 19th, we plan to have to project review meeting.
* By November 21st, we will start cleaning the data and creating code chunks to begin analysis. We will also start creating the webpage
* Between November 23rd and November 28th, we plan to take a break to observe Thanksgiving!
* On November 29th, we plan to continue analyzing the data if needed, and begin on the written report
* By December 1st, we will finalize the webpage
* On December 3rd or 4th, we will record the screencast for our project
* On December 5th, we will do a final run through of all our project materials and make adjustments, if needed. We will also complete the Peer Assessment. 




